os:
  - linux
  - osx

dist: bionic
sudo: required

language: cpp

branches:
  only:
  - development
  - master
  - "/feature.*/"
  - "/hotfix.*/"

matrix:
  allow_failures:
    - osx_image: xcode10.2
      sudo: required
      python: 3.7
      env: BADGE=osx
    - os: linux
      language: generic
      python: 3.7
      env: BADGE=linux

addons:
  apt:
    packages:
      - cmake
      - g++-8
    sources: &sources
      - ubuntu-toolchain-r-test

before_install:
  #- python --version
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      #source ~/virtualenv/python3.7/bin/activate
      eval "CC=gcc-8 && CXX=g++-8"
      export CC=gcc-8
      export CXX=g++-8
      ln -s $(which gcc-8) gcc
      ln -s $(which g++-8) g++
      ln -s $(which g++-8) c++
      export PATH=$(pwd):$PATH
    fi
  #- python3 --version
  - c++ --version

script:
  - cp .travis.modules.txt modules.txt
  - ls
  - sh tools/setup.cmd
  #- python3 pythonTools/mbuild.py -g make
  - ./mbuild
